# Generated by Django 3.0 on 2021-01-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(choices=[('cse', 'CSE'), (' mec', 'MEC'), ('ece', 'ECE'), ('eee', 'EEE'), ('civil', 'CIVIL')], max_length=10, unique=True),
        ),
    ]
