# Generated by Django 3.0 on 2021-01-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20210117_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
