# Generated by Django 3.0 on 2021-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20210117_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
